### ISSUE TITLE
include only specific files and keep the rest

### ISSUE THREAD

**Issue by Roxgame95** [ghostdevv/rollup-obfuscator#110]
How to include inly specific files to be obfuscated and let the rest i don't want to obfuscate the whole bundle file it increase the files size
any example ! 
thank you

**Comment by ghostdevv** [comment]
You should be able to use the new filter option: https://github.com/ghostdevv/rollup-obfuscator#config

**Comment by Roxgame95** [comment]
let say am using include option would the rest of scripts excluded automatically 

include : ["script1.svelte","script1.svelte"];

**Comment by Roxgame95** [comment]
i found my self using version 2 whish doesn't have include or exclude
