### ISSUE TITLE
version 2.1

### ISSUE THREAD

**Issue by Roxgame95** [ghostdevv/rollup-obfuscator#111]
i just update from version 2 to 2.1 and leave same settings the obfuscated file grow dramatically from 500 kb to 3 mb that is very weird !

**Comment by ghostdevv** [comment]
Hey, can you please try with version `2.1.1`

**Comment by Roxgame95** [comment]
i just tested it the files size now 1 mb not perfect as first time but not that bad thank you brother

**Comment by ghostdevv** [comment]
Np, you can adjust the settings of the obfuscator. If you download the latest version (I pushed a few updates over the last few days) you can set things like the preset so that it will obfuscate less (therefore being smaller)
