### ISSUE TITLE
Argument of type error

### ISSUE THREAD

**Issue by CRC32EX** [ghostdevv/rollup-obfuscator#114]
# Steps to reproduce this issue

1. Init Vue3 project
```
npm init vue@latest
```
![image](https://user-images.githubusercontent.com/25629617/160607472-94954216-5b1b-4c96-93a4-7dee9f195140.png)

2. Install modules
```
cd vue-project
npm install
npm install -D rollup-obfuscator javascript-obfuscator
```

3. Edit vite.config.ts

![image](https://user-images.githubusercontent.com/25629617/164640481-04a97dda-79ec-489a-8e2d-cd66773ce9df.png)

4. Error
```
Argument of type '{ stringArray: true; stringArrayEncoding: \"rc4\"[]; }'
is not assignable to parameter of type 'ObfuscatorPluginOptions'.
Property 'global' is missing in type '{ stringArray: true; stringArrayEncoding: \"rc4\"[]; }'
but required in type 'ObfuscatorPluginOptions'.",
```

![image](https://user-images.githubusercontent.com/25629617/164639547-2fb7b363-fbdc-4d93-bf3c-c93a8302993a.png)

# Environment
- "rollup-obfuscator": "^3.0.0"

**Comment by ghostdevv** [comment]
Can you try in version `3.0.1`, the `global` option isn't defaulting correctly. As a workaround for version `3.0.0` you can just set global to true to make the type error go away

**Comment by CRC32EX** [comment]
`3.0.1` works successfully.
Thank you.

**Comment by ghostdevv** [comment]
Np
