### ISSUE TITLE
Nuxt 3 support?

### ISSUE THREAD

**Issue by eris-vn** [ghostdevv/rollup-obfuscator#135]
I tried it with nuxt 3 but got an error, will it support nuxt 3 in the future

**Comment by ghostdevv** [comment]
Could you provide more details on the error you got? @ERIS-VN

**Comment by ERIS-VN** [comment]
i try with nuxt 3 r11 and it works for me now. tks

**Comment by ERIS-VN** [comment]
Issue with vue router
![image](https://user-images.githubusercontent.com/69683870/192113663-ef203ff5-5178-4518-8cce-2763d747d05e.png)
![image](https://user-images.githubusercontent.com/69683870/192113717-30b74f24-ca3b-4e7a-8884-bcd434a56909.png)
![image](https://user-images.githubusercontent.com/69683870/192113672-09ace207-b625-4078-9893-d24708fa103c.png)

**Comment by ERIS-VN** [comment]
any help :<

**Comment by ghostdevv** [comment]
I will take a look for you tomorrow

**Comment by ghostdevv** [comment]
At a guess it's probably that nuxt can't handle the default obfuscation settings, it's not uncommon - you might wanna try playing with them	to see what happens

**Comment by eris-vn** [comment]
I have tried many ways but it still doesn't work, I have also used some other rollup packages but they either don't obfuscate the script or have errors during the rollup process

**Comment by eris-vn** [comment]
![image](https://user-images.githubusercontent.com/69683870/228938022-37c55ec4-9c69-4b0b-9a80-72c4c3254483.png)

**Comment by ghostdevv** [comment]
If there is an error when trying to run the obfuscated code you will need to edit the obfuscator settings to make it change the code less

**Comment by ghostdevv** [comment]
Going to close this for now, but another recommendation I just thought of would be only running this plugin during the build. Something like this:

```js
import { obfuscator } from 'rollup-obfuscator';

export default defineNuxtConfig({
  devtools: { enabled: true },
  vite: {
    build: {
      rollupOptions: {
        plugins: [obfuscator()]
      }
    }
  }
})
```
