### ISSUE TITLE
Css code is invalid

### ISSUE THREAD

**Issue by 17676160564** [ghostdevv/rollup-obfuscator#137]
vite ： 3.1.0
vue: 3.2.38
rollup-obfuscator ： 3.0.2
Results ： Css code is invalid

**Comment by ghostdevv** [comment]
Hey, I need some more information about how you are using this to help figure out the problem @17676160564

**Comment by 17676160564** [comment]
> 嘿， 我想我有同样的问题。当你有 <style scoped> 时，它生成在 Vue 组件中。标记内部的 CSS 不能使用。也许它可以跳过 Vue 组件中 <style scoped> 内部的混合。您需要更多信息，请告诉我。 谢谢你的出彩工作。

thank you

**Comment by qwe104** [comment]
I've faced the same issue myself.

**Comment by 17676160564** [comment]
> I've faced the same issue myself.

Is there any solution?

**Comment by ghostdevv** [comment]
Do you have any error information? Or a minimal reproduction?

**Comment by 17676160564** [comment]
> Do you have any error information? Or a minimal reproduction?

There is no error message，It's just that the scss in<style lang="scss" scoped>has not taken effect

**Comment by ghostdevv** [comment]
Does it take effect when you disable the obfuscator?

**Comment by 17676160564** [comment]
When disabling the obfuscation program, it does not take effect either

**Comment by 17676160564** [comment]
> Does it take effect when you disable the obfuscator?

When disabling the obfuscation program, it does not take effect either

**Comment by 17676160564** [comment]
> Does it take effect when you disable the obfuscator?

Yes, it has taken effect

**Comment by ghostdevv** [comment]
Can you make a minimal reproduction so I can try and figure out why it's happening? I don't have much experience with vue

**Comment by 17676160564** [comment]
> Can you make a minimal reproduction so I can try and figure out why it's happening? I don't have much experience with vue

Okay, this is my newly created testing project  :  https://github.com/17676160564/test-obfuscator.git

**Comment by ghostdevv** [comment]
@17676160564 The easiest solution I found was to do this options:

```js
obfuscator({
  optionsPreset: 'low-obfuscation',
  stringArray: false
}),
```

**Comment by 17676160564** [comment]
> @17676160564 The easiest solution I found was to do this options:
> 
> ```js
> obfuscator({
>   optionsPreset: 'low-obfuscation',
>   stringArray: false
> }),
> ```

Thanks very much.

**Comment by ghostdevv** [comment]
No problem - am I ok to close this?

**Comment by 17676160564** [comment]
> No problem - am I ok to close this?
Certainly
