### ISSUE TITLE
rollup-obfuscator causing lockdown-install.js null error

### ISSUE THREAD

**Issue by bryaan** [ghostdevv/rollup-obfuscator#140]
Im using rollup-obfuscator on my Vue component library.  I am importing it in a downstream project and getting a null error console message from lockdown-install.js:1:103865

**Comment by ghostdevv** [comment]
I probably wouldn't recommend obfuscating the library, but at any rate, you'll probably need to mess around with the obfuscation settings a bit. It's unfortunately not perfect and will cause errors as it changes the code so much

**Comment by ghostdevv** [comment]
Just released v4 and worth giving it a try with that, although I don't imagine it will fix your issue - you'll still need to change your settings

**Comment by ghostdevv** [comment]
Gonna close this for inactivity, feel free to reopen if it still occurs :pray:
