### ISSUE TITLE
Problem with Vite's `import.meta.env.DEV`

### ISSUE THREAD

**Issue by raphaelmenges** [ghostdevv/rollup-obfuscator#144]
Hello 👋

I am using `rollup-obfuscator` in combination with Vite and Electron. When upgrading from version `3.0.2` to `4.0.0` I was prompted with the following error:

```
TypeError: Cannot read properties of undefined (reading 'DEV')
    at Object.<anonymous> (app/packages/main/dist/index.cjs:44:83)
```

The corresponding line in `index.cjs` starts like following:

```
const PROD_URL_ALIAS = "local", ALLOWED_ORIGINS_AND_PERMISSIONS = new Map((void 0)["DEV"] && (void 0)["VITE_DEV_SERVER_URL"]...
```

I assume it has something to do with how `import.meta.env.DEV` of Vite is obfuscated. According to the [docs of Vite](https://vitejs.dev/guide/env-and-mode.html#production-replacement), `import.meta.env` should *not* be accessed with array brackets. I guess some default in `rollup-obfuscator` or its dependencies was changed, such that it transforms `import.meta.env.DEV` differently than before?

**Comment by ghostdevv** [comment]
I can take a look into this later this week but at a guess it's running before vite is doing it's import.meta.env replacements, which is wrong

**Comment by raphaelmenges** [comment]
I have reproduced the issue using a popular [vite+electron template](https://github.com/cawa-93/vite-electron-builder) in minimal fashion: <https://github.com/raphaelmenges/rollup-obfuscator-bug>

With `rollup-obfuscator` [in version 3.0.2](https://github.com/raphaelmenges/rollup-obfuscator-bug/commit/b425559455ae928acb142e15b327c781025ffc6b) it works, with `rollup-obfuscator` [in version 4.0.0](https://github.com/raphaelmenges/rollup-obfuscator-bug/commit/467f18d69dd337204410106b458f1f3a17342bec) the error is thrown upon `npm run watch`.

**Comment by raphaelmenges** [comment]
I could [fix it](https://github.com/raphaelmenges/rollup-obfuscator-bug/commit/1a39b3ed2f98daa6bfe2610983fab97107c3ae23?diff=split) when importing it in Vite as following:

```js
plugins: [
  {
    ...obfuscator({
      sourceMap: process.env.MODE === 'development',
      exclude: ['./node_modules/**/*'],
      target: 'node',
    }),
    enforce: 'post',
  },
  ...
],
```

See the [Vite documentation](https://vitejs.dev/guide/using-plugins.html) for more information about the `enforce` setting. I am not sure whether such option can be set in an `rollup-plugin`, or whether one would need a `vite-plugin`.

**Comment by ghostdevv** [comment]
@raphaelmenges that's a great find! Do you want to send over a PR? I don't imagine it'll cause any issues with rollup. If you do a pr you can check this by doing `pnpm dev` in the repo and check for errors, as that runs the rollup dev environment.

**Comment by ghostdevv** [comment]
It might also be ideal if we add `apply: 'build'`, as it's pointless running in dev
